[package]
name = "knn-rust-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
rand = "0.8.5"
ash = { version = "0.37.0", default-features = false, features = ["loaded", "debug"] }
gpu-allocator = "0.21.0"

[[bin]]
name = "demo"
path = "demos/demo.rs"
